### ISSUE TITLE
Size of WMS requests on mobile devices

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2654]
With NGEO mobile application, the size parameters of WMS (internal or external) requests are very high... 

For example, with a Galaxy S6, we have WIDTH=2160&HEIGHT=3354, 

while on a big desktop screen (24''), we have something like WIDTH=2400&HEIGHT=900

I imagine this is related to high resolution of mobile devices... but this has 2 consequences : 
1°/ Requests speed are low on mobile devices
2°/ Size of labels defined in pixels for external WMS layers is too small and not readable on the device

**Comment by sbrunner** [comment]
first for #2:
* We should add the missing DPI parameter...

for #1:
* #2 should make the requests a little bit faster because we will have less displayed object.
* I think that the WMS speed isn't a relay issue, the more important is that the base layers (in WMTS) will be displayed relay quickly.
* If we do something it will naturally be for a lower quality...

I purpose that we fix #2, then see what we will do with #1.

**Comment by gnerred** [comment]
Ok with your proposal, so I wait next 2.1 release to test. Do you have already planned the next 2.1 release ?

**Comment by fredj** [comment]
See also #2544

**Comment by fredj** [comment]
About the labels size: the dpi parameter is correctly passed to mapserver (`MAP_RESOLUTION=270` in my case).
Maybe something is missing in the mapserver configuration? (http://mapserver.org/ru/development/rfc/ms-rfc-55.html)

**Comment by gnerred** [comment]
It is not related to mapserver, but to QGIS server. How do you see this MAP_RESOLUTION ? Here is an example of request sent 

https://preprod.cartoriviera.ch/preprod/wsgi/mapserv_proxy?ogcserver=source+for+https%3A%2F%2Fpreprod.cartoriviera.ch%2Fqgis%2Fqgis_mapserver.fcgi%3Fmap%3D%2Fvar%2Fsig%2Fqgis%2Fexport.qgs%26transparent%3Dtrue+image%2Fpng&cache_version=d9970d141dd5433e9cf0591259f37c5d&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=export_reach&SERVERTYPE=mapserver&CRS=EPSG%3A21781&STYLES=&WIDTH=2520&HEIGHT=827&BBOX=553543%2C145287.375%2C554803%2C145700.625

**Comment by sbrunner** [comment]
@fredj 
In this case the DPI parameter is missing ...

**Comment by fredj** [comment]
@gnerred in the admin interface, can you check if this OGCServer "Server type" is QGISserver ?

**Comment by gnerred** [comment]
No it was mapserver... I changed to QGISserver and now it works fine, thanks :O) !

**Comment by gnerred** [comment]
Oh sorry, the problem of printing remains : https://github.com/camptocamp/c2cgeoportal/issues/2962

**Comment by sbrunner** [comment]
Finally it an issue when you print a qgis layer with cgxp?

**Comment by gnerred** [comment]
Yes it is still an issue. To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/s/Hvds
2°/ Do a print on the red lines -> symbols are too small in PDF result

**Comment by fredj** [comment]
In the data sent to the print server, `serverType` is still `mapserver`:
```
...
{
  baseUrl: "https://preprod.cartoriviera.ch/qgis/qgis_mapserver.fcgi?map=/var/sig/qgis/export.qgs&transparent=true",
  customParams: {...},
  serverType: "mapserver",
  ...
}
...
```

**Comment by gnerred** [comment]
I my database, it seems to be configured correcty : 
![image](https://cloud.githubusercontent.com/assets/1989467/26719596/70b51ad2-4785-11e7-90e5-6a30eb15c6eb.png)

**Comment by sbrunner** [comment]
But your using the CGXP interface who don't use this table ...

**Comment by gnerred** [comment]
So where is it configured ? It seems that it cannot be configured in admin interface, right ? So you have to fix it in the code ?

**Comment by fredj** [comment]
The problem is that the print in the CGXP interface doesn't use the server type; the value is fixed to `mapserver`.

See:
https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/Print.js#L344-L347

**Comment by gnerred** [comment]
So what is the solution ?

**Comment by gnerred** [comment]
Ok thanks @fredj , I wait your next feed-back

**Comment by sbrunner** [comment]
For me thats looks good :-)

**Comment by gnerred** [comment]
I've installed latest 2.2.0.dev13, but there is still a problem on mobile device with QGIS layers. Will it be fixed in this issue ? 
![image](https://user-images.githubusercontent.com/1989467/28927059-d3ab1b0e-7869-11e7-8d98-0c06f0e2caf3.png)

**Comment by ybolognini** [comment]
@sbrunner will check if ngeo sends the right dpi parameters to QGIS

**Comment by ybolognini** [comment]
Now print issue has been added here: https://github.com/camptocamp/ngeo/issues/2793

This issue concerns mobile dpi issue only.

**Comment by sbrunner** [comment]
@gnerred in the admin interface I change the server type to QGIS, and it seem working :-)

This should be done manually after running the themev1tov2 script.

**Comment by gnerred** [comment]
OK fine thanks ! So it will be great if script themev1tov2 could be adapted to automatically set server type to QGIS if base URL of layer V1 contains "qgis_mapserver.fcgi". What do you think ? Because each manual step if one more chance to have problems...

**Comment by sbrunner** [comment]
Replaced by https://github.com/camptocamp/c2cgeoportal/issues/3015
